-- basic 
-- Total Users by Traffic Source
-- Which traffic source brings the most users?

SELECT source_medium, SUM(users) AS total_users
FROM web_traffic_clean
GROUP BY source_medium
ORDER BY total_users DESC;

-- Monthly Traffic Trend
-- How does website traffic change month by month?

SELECT year, month, SUM(users) AS total_users
FROM web_traffic_clean
GROUP BY year, month
ORDER BY year, month;

-- Average Bounce Rate per Source
-- Which source has the lowest bounce rate?

SELECT source_medium, ROUND(AVG(bounce_rate),2) AS avg_bounce_rate
FROM web_traffic_clean
GROUP BY source_medium
ORDER BY avg_bounce_rate;

-- Total Revenue Generated
-- What is the total revenue generated by the website?

SELECT SUM(revenue) AS total_revenue
FROM web_traffic_clean;

-- Top 3 Revenue Months
-- Which months generated the highest revenue?

SELECT year, month, SUM(revenue) AS revenue
FROM web_traffic_clean
GROUP BY year, month
ORDER BY revenue DESC
LIMIT 3;

-- intermediate
-- Conversion Rate by Traffic Source
-- Which source converts best?

SELECT source_medium,
       ROUND(AVG(conversion_rate),2) AS avg_conversion_rate
FROM web_traffic_clean
GROUP BY source_medium
ORDER BY avg_conversion_rate DESC;

-- New vs Returning Users
-- What percentage of users are new users per source?

SELECT source_medium,
       ROUND(SUM(new_users) * 100.0 / SUM(users), 2) AS new_user_percentage
FROM web_traffic_clean
GROUP BY source_medium;

-- Engagement Quality Ranking
-- Rank sources by average session duration.

SELECT source_medium,
       SEC_TO_TIME(AVG(TIME_TO_SEC(avg_session_duration))) AS avg_session_time
FROM web_traffic_clean
GROUP BY source_medium
ORDER BY avg_session_time DESC;

-- Revenue per User
-- Which source generates the highest revenue per user?

SELECT source_medium,
       ROUND(SUM(revenue) / SUM(users), 2) AS revenue_per_user
FROM web_traffic_clean
GROUP BY source_medium
ORDER BY revenue_per_user DESC;

-- Bounce Rate vs Conversion
-- Do sources with lower bounce rate convert better?

SELECT source_medium,
       ROUND(AVG(bounce_rate),2) AS avg_bounce_rate,
       ROUND(AVG(conversion_rate),2) AS avg_conversion_rate
FROM web_traffic_clean
GROUP BY source_medium;

-- advace
-- Rank Traffic Sources by Revenue (Window Function)

SELECT source_medium,
       SUM(revenue) AS total_revenue,
       RANK() OVER (ORDER BY SUM(revenue) DESC) AS revenue_rank
FROM web_traffic_clean
GROUP BY source_medium;

-- Month-over-Month Revenue Growth

SELECT year, month,
       SUM(revenue) AS revenue,
       SUM(revenue) - LAG(SUM(revenue)) OVER (ORDER BY year, month) AS mom_growth
FROM web_traffic_clean
GROUP BY year, month;

-- High Traffic but Low Conversion Sources
-- (Optimization Opportunity)

SELECT source_medium,
       SUM(users) AS users,
       ROUND(AVG(conversion_rate),2) AS avg_conversion_rate
FROM web_traffic_clean
GROUP BY source_medium
HAVING users > (SELECT AVG(users) FROM web_traffic_clean)
   AND avg_conversion_rate < (SELECT AVG(conversion_rate) FROM web_traffic_clean);

-- Revenue Contribution Percentage by Source
SELECT source_medium,
       ROUND(SUM(revenue) * 100.0 / 
            (SELECT SUM(revenue) FROM web_traffic_clean), 2) AS revenue_share_pct
FROM web_traffic_clean
GROUP BY source_medium;

-- Best Performing Source per Year
SELECT *
FROM (
    SELECT year,
           source_medium,
           SUM(revenue) AS revenue,
           RANK() OVER (PARTITION BY year ORDER BY SUM(revenue) DESC) AS rnk
    FROM web_traffic_clean
    GROUP BY year, source_medium
) t
WHERE rnk = 1;
